CREATE TABLE sport_events (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              description VARCHAR(255) NOT NULL,
                              home_team VARCHAR(100) NOT NULL,
                              away_team VARCHAR(100) NOT NULL,
                              start_time TIMESTAMP NOT NULL,
                              sport VARCHAR(50) NOT NULL,
                              country VARCHAR(50) NOT NULL,
                              competition VARCHAR(100) NOT NULL,
                              settled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE markets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         description VARCHAR(255) NOT NULL,
                         status VARCHAR(10) NOT NULL CHECK (status IN ('OPEN', 'CLOSED')),
                         settled BOOLEAN NOT NULL DEFAULT FALSE,
                         sport_event_id BIGINT NOT NULL,
                         FOREIGN KEY (sport_event_id) REFERENCES sport_events(id) ON DELETE CASCADE
);

CREATE TABLE outcomes (
                          id BIGSERIAL PRIMARY KEY,
                          description VARCHAR(255) NOT NULL,
                          settled BOOLEAN NOT NULL DEFAULT FALSE,
                          price DOUBLE PRECISION NOT NULL,
                          result VARCHAR(10) CHECK (result IN ('WIN', 'LOSE', 'NULL') OR result IS NULL),
                          market_id BIGINT NOT NULL,
                          FOREIGN KEY (market_id) REFERENCES markets(id) ON DELETE CASCADE
);


INSERT INTO sport_events (description, home_team, away_team, start_time, sport, country, competition, settled)
VALUES
    ('Arsenal v Manchester United', 'Arsenal', 'Manchester United', '2025-01-31 18:00:00', 'Football', 'England', 'Premier League', FALSE),
    ('Liverpool v Chelsea', 'Liverpool', 'Chelsea', '2025-02-01 15:00:00', 'Football', 'England', 'Premier League', FALSE);

INSERT INTO markets (description, status, settled, sport_event_id)
VALUES
    ('Match Betting', 'OPEN', FALSE, 1),
    ('Over/Under 2.5 Goals', 'OPEN', FALSE, 1);

INSERT INTO outcomes (description, settled, price, result, market_id)
VALUES
    ('Arsenal to win', FALSE, 2.0, NULL, 1),
    ('Draw', FALSE, 3.5, NULL, 1),
    ('Manchester United to win', FALSE, 2.8, NULL, 1),
    ('Over 2.5 Goals', FALSE, 1.9, NULL, 2);